services:
  psinode:
    image: "jamesmart/psidekick-psinode"
    user: root
    ports:
      - '8080:8080'
    volumes:
      - type: volume
        source: psinode-volume
        target: /root

volumes:
  psinode-volume:
