services:
  psinode:
    image: "ghcr.io/gofractally/psinode-ubuntu-2004"
    user: root
    ports:
      - '8080:8080'
    volumes:
      - type: volume
        source: psinode-volume
        target: /root

volumes:
  psinode-volume:
