version: '3.8'

name: psibase

services:
  psinode:
    build:
      context: .
      dockerfile: ./psinode.Dockerfile
    user: root
    ports:
      - '8080:8080'
    volumes:
      - type: volume
        source: psinode-volume
        target: /root
  code:
    build:
      context: .
      dockerfile: ./code.Dockerfile
    user: root
    command: sleep infinity
    volumes:
      - type: volume
        source: code-volume
        target: /root
      - ../../artifacts:/root/projects/artifacts/
    depends_on:
      - psinode

volumes:
  psinode-volume:
  code-volume:
