#!/bin/bash
IMAGE=jamesmart/psidekick
TAG=0.1.3
BUILDER=buildx-multi-arch

./prepare-buildx
#docker pull $IMAGE:$TAG && echo "Failure: Tag already exists" || docker buildx build --push --no-cache --builder=$BUILDER --platform=linux/amd64,linux/arm64 --build-arg TAG=$TAG --tag=$IMAGE:$TAG ../
docker buildx build --push --no-cache --builder=$BUILDER --platform=linux/amd64,linux/arm64 --build-arg TAG=$TAG --tag=$IMAGE:$TAG ../
