[package]
name = "__service__"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
psibase = "0.1.6"
serde = { version = "1.0.149", features = ["derive"] }
